import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffdea5",
        "on-tertiary-container": "#838484",
        "primary-fixed": "#e5e2e1",
        "on-primary-fixed-variant": "#474746",
        "on-tertiary-fixed": "#1a1c1c",
        "surface": "#fbf9f9",
        "primary-fixed-dim": "#c8c6c5",
        "tertiary": "#000000",
        "on-primary-container": "#858383",
        "on-tertiary-fixed-variant": "#454747",
        "outline": "#747878",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#efeded",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e3e2e2",
        "on-primary-fixed": "#1c1b1b",
        "background": "#fbf9f9",
        "inverse-on-surface": "#f2f0f0",
        "secondary": "#775a19",
        "secondary-fixed-dim": "#e9c176",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-surface-variant": "#444748",
        "on-secondary-container": "#785a1a",
        "on-error": "#ffffff",
        "surface-variant": "#e3e2e2",
        "tertiary-container": "#1a1c1c",
        "tertiary-fixed": "#e2e2e2",
        "inverse-surface": "#303031",
        "secondary-container": "#fed488",
        "surface-bright": "#fbf9f9",
        "inverse-primary": "#c8c6c5",
        "on-secondary-fixed-variant": "#5d4201",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#261900",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-background": "#1b1c1c",
        "primary-container": "#1c1b1b",
        "outline-variant": "#c4c7c7",
        "surface-container-low": "#f5f3f3",
        "surface-tint": "#5f5e5e",
        "on-primary": "#ffffff",
        "surface-container-high": "#e9e8e7",
        "on-surface": "#1b1c1c",
        "error-container": "#ffdad6",
        "primary": "#000000",
        "surface-dim": "#dbdad9"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg-custom": "40px",
        "gutter": "16px",
        "sm-custom": "16px",
        "xl-custom": "64px",
        "margin-mobile": "20px",
        "md-custom": "24px",
        "base-custom": "4px",
        "xs-custom": "8px"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"]
      },
    },
  },
  plugins: [],
};
export default config;
